name: drift_isolate
description: drift isolate
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  drift_dev: 1.7.0
  faker: ^2.0.0
  flutter:
    sdk: flutter

  path_provider: ^2.0.11
  sqlite3_flutter_libs: 0.5.0

dev_dependencies:
  build_runner: 2.2.0
  flutter_test:
    sdk: flutter
  surf_lint_rules: 1.5.0

flutter:
  uses-material-design: true
